getwd()
#setwd("C:/Users/Anna/Github/Biology")

library(biomaRt)

ensembl_mart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

chromosome1 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "1", mart = ensembl_mart)
chromosome2 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "2", mart = ensembl_mart)
chromosome3 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "3", mart = ensembl_mart)
chromosome4 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "4", mart = ensembl_mart)
chromosome5 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "5", mart = ensembl_mart)
chromosome6 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "6", mart = ensembl_mart)
chromosome7 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "7", mart = ensembl_mart)
chromosome8 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "8", mart = ensembl_mart)
chromosome9 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "9", mart = ensembl_mart)
chromosome10 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "10", mart = ensembl_mart)
chromosome11 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "11", mart = ensembl_mart)
chromosome12 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "12", mart = ensembl_mart)
chromosome13 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "13", mart = ensembl_mart)
chromosome14 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "14", mart = ensembl_mart)
chromosome15 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "15", mart = ensembl_mart)
chromosome16 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "16", mart = ensembl_mart)
chromosome17 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "17", mart = ensembl_mart)
chromosome18 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "18", mart = ensembl_mart)
chromosome19 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "19", mart = ensembl_mart)
chromosome20 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "20", mart = ensembl_mart)
chromosome21 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "21", mart = ensembl_mart)
chromosome22 <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "22", mart = ensembl_mart)
chromosomeX <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "x", mart = ensembl_mart)
chromosomeY <- getBM(filters = "chromosome_name", attributes = ("hgnc_symbol"), values = "y", mart = ensembl_mart)

write.csv(chromosome1, file = "chromosome1.csv")
write.csv(chromosome2, file = "chromosome2.csv")
write.csv(chromosome3, file = "chromosome3.csv")
write.csv(chromosome4, file = "chromosome4.csv")
write.csv(chromosome5, file = "chromosome5.csv")
write.csv(chromosome6, file = "chromosome6.csv")
write.csv(chromosome7, file = "chromosome7.csv")
write.csv(chromosome8, file = "chromosome8.csv")
write.csv(chromosome9, file = "chromosome9.csv")
write.csv(chromosome10, file = "chromosome10.csv")
write.csv(chromosome11, file = "chromosome11.csv")
write.csv(chromosome12, file = "chromosome12.csv")
write.csv(chromosome13, file = "chromosome13.csv")
write.csv(chromosome14, file = "chromosome14.csv")
write.csv(chromosome15, file = "chromosome15.csv")
write.csv(chromosome16, file = "chromosome16.csv")
write.csv(chromosome17, file = "chromosome17.csv")
write.csv(chromosome18, file = "chromosome18.csv")
write.csv(chromosome19, file = "chromosome19.csv")
write.csv(chromosome20, file = "chromosome20.csv")
write.csv(chromosome21, file = "chromosome21.csv")
write.csv(chromosome22, file = "chromosome22.csv")
write.csv(chromosomeX, file = "chromosomeX.csv")
write.csv(chromosomeY, file = "chromosomeY.csv")